/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include "stm32f4xx.h"
#include "system_stm32f4xx.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
	SystemInit();
	// enable gpiod clock (in AHB1ENR)
	RCC->AHB1ENR |= BV(3);
	// set gpiod pin 14 as output (in MODER)
	GPIOD->MODER &= ~BV(29);
	GPIOD->MODER |= BV(28);
	// set gpiod pin 14 speed to low (in OSPEEDR)
	GPIOD->OSPEEDR &= ~(BV(29) | BV(28));
	// set gpiod pin 14 no pull up, no pull down (in PUPDR)
	GPIOD->PUPDR &= ~(BV(29) | BV(28));
	// set gpiod pin 14 type as push-pull (in OTYPER)
	GPIOD->OTYPER &= ~BV(14);

	while(1) {
		// set gpiod pin 14 -- Red LED ON
		GPIOD->ODR |= BV(14);
		// delay 1000 ms
		DelayMs(1000);
		// clear gpiod pin 14 -- Red LED OFF
		GPIOD->ODR &= ~BV(14);
		// delay 1000 ms
		DelayMs(1000);
	} // repeat the ON/OFF

	return 0;
}



